apiVersion: v1
kind: Namespace
metadata:
  name: app-database-center
  labels:
    name: app-database-center
---
apiVersion: v1
kind: Service
metadata:
  name: pg-svc
  namespace: app-database-center
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5001
      targetPort: postgres-port
      protocol: TCP
      name: postgres-svc
---

